/**
 * Types for the meanings layer (English + Malayalam translations).
 *
 * Per docs/meanings-plan.md, every bhāṣya unit (mantra / sūtra /
 * verse / kārikā) and the bhāṣya prose blocks under it can carry
 * translations in two languages and one or more authoritative
 * sources. The data is keyed per text-slug so it can be lazy-loaded
 * alongside the chapter chunks.
 *
 * File layout:
 *   public/data/meanings/<text-slug>.json     — single file per text
 *
 * The file is a flat unitId → MeaningUnit map; entries for blocks
 * live under a synthetic `<unitId>::block-<n>` key (n = 0-based
 * index into BhashyaUnit.blocks). This keeps the file flat and
 * cheap to parse.
 */

export type MeaningLanguage = 'en' | 'ml';

export interface MeaningSource {
  /** Stable short id, e.g. "gambhirananda", "sastri-pd", "sringeri-ml". */
  id: string;
  /** Translator + book name as it should appear on screen. */
  citation: string;
  /** License the text is bundled under. */
  license:
    | 'public-domain'
    | 'cc-by'
    | 'cc-by-sa'
    | 'permission'
    | 'fair-use'
    /** AI-generated draft awaiting reviewer sign-off; never authoritative. */
    | 'ai-draft';
  /** Year of publication or first issue, ISO 8601 date. */
  publishedAt?: string;
  /** True for the Sanskrit-original side ("the bhāṣya defines its own meaning"). */
  isPrimary?: boolean;
  /** Set when generated by an LLM; the reader UI surfaces this prominently. */
  aiGenerated?: {
    model: string;
    generatedAt: string;
    /** Free-text caveat shown next to the entry. */
    caveat: string;
  };
}

export interface MeaningEntry {
  language: MeaningLanguage;
  /** Translation text. May contain newlines and basic punctuation. */
  text: string;
  /** Reference into MeaningsFile.sources. */
  sourceId: string;
  /** Optional translator's note for THIS unit. */
  note?: string;
}

export interface MeaningUnit {
  /** Either a unitId (e.g. "IS_C01_V01") or "<unitId>::block-<n>". */
  key: string;
  /** Highest-level summary, language-tagged. Order: primary first. */
  entries: MeaningEntry[];
}

export interface MeaningsFile {
  slug: string;
  /** Build-time stamp. */
  generatedAt: string;
  /** Catalog of every source referenced by `entries[].sourceId`. */
  sources: MeaningSource[];
  /** Map keyed by `key` for O(1) lookup. */
  units: Record<string, MeaningUnit>;
}
